group_imports = "StdExternalCrate"
imports_granularity = "Crate"
format_code_in_doc_comments = true
use_field_init_shorthand = true
fn_params_layout = "Compressed"
wrap_comments = true
comment_width = 100
